<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-0QEPCK00" failures="1" tests="5" name="Listener Test Case" time="0.048" errors="0" timestamp="07 Apr 2024 18:39:43 GMT">
  <testcase classname="com.testng.listeners.Sample" name="testFour" time="0.009">
    <skipped/>
  </testcase> <!-- testFour -->
  <testcase classname="com.testng.listeners.Sample" name="testGetData" time="0.001"/>
  <testcase classname="com.testng.listeners.Sample" name="testGetData" time="0.001"/>
  <testcase classname="com.testng.listeners.Sample" name="testOne" time="0.001"/>
  <testcase classname="com.testng.listeners.Sample" name="testThree" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [7] but found [5]">
      <![CDATA[java.lang.AssertionError: expected [7] but found [5]
at com.testng.listeners.Sample.testThree(Sample.java:26)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testThree -->
</testsuite> <!-- Listener Test Case -->
